# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

  SetupAndLinting:
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: user1
          minimum-approvals: 1
          issue-title: "need approval for rollback"
          exclude-workflow-initiator-as-approver: false

      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
